// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8gnwtjkLW8tKSaZoivVLPtnKLT1T9pY',
    appId: '1:845970661091:web:dc33c8185258108631efd6',
    messagingSenderId: '845970661091',
    projectId: 'matchifiy',
    authDomain: 'matchifiy.firebaseapp.com',
    storageBucket: 'matchifiy.firebasestorage.app',
    measurementId: 'G-SW4E6XVS9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbMhmCqQs0yI10iFrDVlqAcdwlqe12EAE',
    appId: '1:845970661091:android:4c504b2280c4f2dd31efd6',
    messagingSenderId: '845970661091',
    projectId: 'matchifiy',
    storageBucket: 'matchifiy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswzx1b-P3CFiDIDDKVBIm3V-8lvUJxIk',
    appId: '1:845970661091:ios:452c81303f021b7531efd6',
    messagingSenderId: '845970661091',
    projectId: 'matchifiy',
    storageBucket: 'matchifiy.firebasestorage.app',
    androidClientId:
        '845970661091-0j9ovvar6nqes3n0vjp7tpvgs0ovjf33.apps.googleusercontent.com',
    iosClientId:
        '845970661091-3h760m08f1gen71fl6rfnmbtrcshrk78.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchifiy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBswzx1b-P3CFiDIDDKVBIm3V-8lvUJxIk',
    appId: '1:845970661091:ios:452c81303f021b7531efd6',
    messagingSenderId: '845970661091',
    projectId: 'matchifiy',
    storageBucket: 'matchifiy.firebasestorage.app',
    androidClientId:
        '845970661091-0j9ovvar6nqes3n0vjp7tpvgs0ovjf33.apps.googleusercontent.com',
    iosClientId:
        '845970661091-3h760m08f1gen71fl6rfnmbtrcshrk78.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchifiy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj8gnwtjkLW8tKSaZoivVLPtnKLT1T9pY',
    appId: '1:845970661091:web:230d062d5d42557631efd6',
    messagingSenderId: '845970661091',
    projectId: 'matchifiy',
    authDomain: 'matchifiy.firebaseapp.com',
    storageBucket: 'matchifiy.firebasestorage.app',
    measurementId: 'G-2KRC1GCC77',
  );
}
